/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.procesador_de_archivos_de_logs;

/**
 *
 * @author yojan
 */

import java.lang.String;
import javax.swing.JOptionPane;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import javax.mail.MessagingException;
public class Pantalla_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Pantalla_Principal
     */
    public Pantalla_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Tf_Ruta_Logs = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tf_Ruta_Rar = new javax.swing.JTextField();
        Btn_Gen_Logs = new javax.swing.JButton();
        Gen_Proc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Tf_Ruta_Rar1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Lbl_Cantidad_Errores = new javax.swing.JLabel();
        Lbl_Cantidad_S_Errores = new javax.swing.JLabel();
        Lbl_Anal = new javax.swing.JLabel();
        Lbl_Comp = new javax.swing.JLabel();
        Lbl_Correo = new javax.swing.JLabel();
        Txt_Logs = new javax.swing.JScrollPane();
        txt_Results = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Procesamiento de Archivos en Paralelo");
        setBackground(new java.awt.Color(51, 204, 255));
        setLocationByPlatform(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ruta de los Logs");

        Tf_Ruta_Logs.setToolTipText("Inserte la ruta de los logs en formato TXT");
        Tf_Ruta_Logs.setMaximumSize(new java.awt.Dimension(64, 22));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ruta de los Archivos Comprimidos");

        Tf_Ruta_Rar.setToolTipText("Inserte la ruta de los logs en formato TXT");
        Tf_Ruta_Rar.setMaximumSize(new java.awt.Dimension(64, 22));

        Btn_Gen_Logs.setText("Generar Logs");
        Btn_Gen_Logs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Gen_LogsActionPerformed(evt);
            }
        });

        Gen_Proc.setText("Ejecutar Procesos");
        Gen_Proc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Gen_ProcActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enviar Archivos al Correo:");

        Tf_Ruta_Rar1.setToolTipText("Inserte la ruta de los logs en formato TXT");
        Tf_Ruta_Rar1.setMaximumSize(new java.awt.Dimension(64, 22));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tf_Ruta_Rar1, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tf_Ruta_Logs, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Tf_Ruta_Rar, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gen_Proc)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Btn_Gen_Logs)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Tf_Ruta_Logs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Gen_Logs))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tf_Ruta_Rar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gen_Proc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Tf_Ruta_Rar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204)));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        Lbl_Cantidad_Errores.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Lbl_Cantidad_Errores.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Cantidad_Errores.setText("Logs con Errores:");

        Lbl_Cantidad_S_Errores.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Lbl_Cantidad_S_Errores.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Cantidad_S_Errores.setText("Logs sin Errores:");

        Lbl_Anal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Lbl_Anal.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Anal.setText("Tiempo de Análisis de Archivos:");

        Lbl_Comp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Lbl_Comp.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Comp.setText("Tiempo de Compresión de Archivos:");

        Lbl_Correo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        Lbl_Correo.setForeground(new java.awt.Color(255, 255, 255));
        Lbl_Correo.setText("Tiempo de Envío de Correo:");

        txt_Results.setColumns(50);
        txt_Results.setRows(20);
        Txt_Logs.setViewportView(txt_Results);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Resultados:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_Logs)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Cantidad_Errores)
                            .addComponent(Lbl_Cantidad_S_Errores))
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_Correo)
                            .addComponent(Lbl_Anal)
                            .addComponent(Lbl_Comp))
                        .addGap(0, 270, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Lbl_Anal)
                        .addGap(18, 18, 18)
                        .addComponent(Lbl_Comp))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(Lbl_Cantidad_Errores)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Lbl_Cantidad_S_Errores)
                        .addGap(11, 11, 11))
                    .addComponent(Lbl_Correo, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(Txt_Logs, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Gen_LogsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Gen_LogsActionPerformed
        // TODO add your handling code here:
        String ruta_logs    =   Pantalla_Principal.this.Tf_Ruta_Logs.getText();
        if(ruta_logs.length()   >   0){
            txt_Results.setText(txt_Results.getText()+GenerarArchivos.main(ruta_logs));
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe rellenar el campo de la ruta de los logs.");
            Pantalla_Principal.this.Tf_Ruta_Logs.grabFocus();
        }
    }//GEN-LAST:event_Btn_Gen_LogsActionPerformed

    private void Gen_ProcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Gen_ProcActionPerformed
        // TODO add your handling code here:
        String ruta_logs    =   Pantalla_Principal.this.Tf_Ruta_Logs.getText();
        String ruta_comp    =   Pantalla_Principal.this.Tf_Ruta_Rar.getText();
        if(ruta_logs.length()   >   0){
            iniciarProcesos(ruta_logs, ruta_comp);
        }
        else{
            JOptionPane.showMessageDialog(null, "Debe rellenar el campo de la ruta de los logs.");
            Pantalla_Principal.this.Tf_Ruta_Logs.grabFocus();
        }
    }//GEN-LAST:event_Gen_ProcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Principal().setVisible(true);
            }
        });
    }
    
    public void iniciarProcesos(String ruta, String ruta_cmp) {
        ExecutorService executorService = Executors.newFixedThreadPool(3);
        //int[] arreglo=new int[2];
        try {
            // Acción 1: Leer archivos
            Runnable proceso1 = () -> {
                long startTime = System.currentTimeMillis();
                //List<File> txtFiles = getTxtFiles();
                int[] arreglo=ContadorLogs.main(ruta);
                long endTime = System.currentTimeMillis();
                String mensaje="\nProceso 1 (Lectura de archivos) terminó en: " + (endTime - startTime) + " ms";
                this.txt_Results.setText(this.txt_Results.getText()+mensaje);
                this.Lbl_Cantidad_Errores.setText("Logs con Errores: "+arreglo[1]);
                this.Lbl_Cantidad_S_Errores.setText("Logs sin Errores: "+arreglo[0]);
                this.Lbl_Anal.setText("Tiempo de Ejecución de Análisis de Archivos: "+(endTime-startTime)+"ms");
            };

            // Acción 2: Compresión
            Runnable proceso2 = () -> {
                long startTime = System.currentTimeMillis();
//                try {
//                    List<File> txtFiles = getTxtFiles();
//                    compressFiles(txtFiles, "archivos_comprimidos.zip");
//                } catch (IOException e) {
//                    e.printStackTrace();
//                }
                ComprimirArchivos.main(ruta, ruta_cmp);
                long endTime = System.currentTimeMillis();
                //System.out.println("Proceso 2 (Compresión de archivos) terminó en: " + (endTime - startTime) + " ms");
                String mensaje="\nProceso 2 (Compresión de archivos) terminó en: " + (endTime - startTime) + " ms";
                this.txt_Results.setText(this.txt_Results.getText()+mensaje);
                this.Lbl_Comp.setText("Tiempo de Ejecución de Compresión de Archivos: "+(endTime-startTime)+"ms");
            };

            // Acción 3: Enviar correo
            Runnable proceso3 = () -> {
                long startTime = System.currentTimeMillis();
//                try {
//                    enviarCorreo();
//                } catch (MessagingException e) {
//                    e.printStackTrace();
//                }
                EnvioCorreo.main(this.Tf_Ruta_Rar1.getText());
                long endTime = System.currentTimeMillis();
                String mensaje="\nProceso 3 (Envío de correo) terminó en: " + (endTime - startTime) + " ms";
                this.txt_Results.setText(this.txt_Results.getText()+mensaje);
                this.Lbl_Correo.setText("Tiempo de Ejecución de Envío de Correo: "+(endTime-startTime)+"ms");
                //System.out.println("Proceso 3 (Envío de correo) terminó en: " + (endTime - startTime) + " ms");
            };

            // Ejecutamos las acciones distintas en paralelo
            executorService.submit(proceso1);
            executorService.submit(proceso2);
            executorService.submit(proceso3);

        } finally {
            executorService.shutdown();
            try {
                if (!executorService.awaitTermination(60, TimeUnit.SECONDS)) {
                    executorService.shutdownNow();
                }
            } catch (InterruptedException e) {
                executorService.shutdownNow();
            }
        }
        String mensaje="\nTodas las acciones han sido ejecutadas en paralelo.";
                this.txt_Results.setText(this.txt_Results.getText()+mensaje);
        //System.out.println("Todas las acciones han sido ejecutadas en paralelo.");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Gen_Logs;
    private javax.swing.JButton Gen_Proc;
    private javax.swing.JLabel Lbl_Anal;
    public javax.swing.JLabel Lbl_Cantidad_Errores;
    public javax.swing.JLabel Lbl_Cantidad_S_Errores;
    public javax.swing.JLabel Lbl_Comp;
    public javax.swing.JLabel Lbl_Correo;
    public javax.swing.JTextField Tf_Ruta_Logs;
    public javax.swing.JTextField Tf_Ruta_Rar;
    public javax.swing.JTextField Tf_Ruta_Rar1;
    public javax.swing.JScrollPane Txt_Logs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JTextArea txt_Results;
    // End of variables declaration//GEN-END:variables
}
